### ISSUE TITLE
About instances_val2017_down1_4

### ISSUE THREAD

**Issue by dzgx** [cuiziteng/ECCV_AERIS#11]
Thank you for your work.
Would you please explain why your instances_val2017_down1_4.json(COCO-d) is larger than instances_val2017.json ?
Is there you add some details to instances_val2017_down1_4.json?

**Comment by cuiziteng** [comment]
Hi, I think this may caused by the number of strings in instances_val2017_down1_4.json(COCO-d), because when I generate  instances_val2017_down1_4.json(COCO-d), it would random downsampling the original bbox labels, so may generate some decimal point (like 233/4 = 28.25).
