### ISSUE TITLE
About Time Of Trian

### ISSUE THREAD

**Issue by dzgx** [cuiziteng/ECCV_AERIS#12]
Thank you for your opening.
I have found you train the model with 4 V100 GPUs.
I want to ask how long you train the model for one time with 4 V100 GPUS and whether you try to reduce the number of  train datasets randomly or you always train the model with 4 V100 GPUS.

**Comment by cuiziteng** [comment]
Hi, it would take between 1~2 days for training on 4 V100 GPUs, besides I make all the experiments on detection to use 4 GPUs.
