### ISSUE TITLE
Need code of coco-d dataset generation

### ISSUE THREAD

**Issue by mubashirITU** [cuiziteng/ECCV_AERIS#13]
I read your paper. It is really helpful for me, Your code implemented in two parts. One is dataset generation from translation and other is detection and regeneration of images. You shared the code of second part only. I need the code for coco-d dataset generation also. I will be very thankful to you.

**Comment by cuiziteng** [comment]
That's a good idea! It's also in my plan to upload the dataset generation code, including generate multi-degradation condition and single degradation condition.

I'll tell you when I upload the final full code, thx~

**Comment by mubashirITU** [comment]
Thanks for your cooperation.
I will be very thankful if you update the code as soon as possible.

**Comment by cuiziteng** [comment]
Sorry for long-time wait.

https://github.com/cuiziteng/ECCV_AERIS/blob/master/data_gen.py
