### ISSUE TITLE
About sr_loss

### ISSUE THREAD

**Issue by dzgx** [cuiziteng/ECCV_AERIS#15]
I have tried your code. IIn your code I have found you used  "losses['sr_losses']" for supervised signal, so I want to ask which file you add the "losses['sr_losses']" to losses.(the underlying code)

**Comment by cuiziteng** [comment]
Hello, all the file have add the "losses['sr_losses']" to losses, because I've wrote it in the code, so all the config of AERIS is add this loss in training.
