### ISSUE TITLE
What are the advantages of the super-resolution module (ARRD module in paper)?

### ISSUE THREAD

**Issue by anonymoussss** [cuiziteng/ECCV_AERIS#18]
In my opinion, using only Down-sampling Degradation Transformations allowed the detection network (both encoder and decoder) to learn the ' intrinsic equivariant representation against various resolutions and degradation'，isn't it? 

What are the advantages of the ARRD module over the trick 'multi-scale training' commonly used in detection training? It seems to just add a supervision.

Is there a mathematical explanation?

**Comment by cuiziteng** [comment]
Many thanks for the valuable question, we use ARRD to constrain that Manifold with Scale invariance, If there is no ARRD, it is a simple data argumentation, and there is no ability to scale invariance. 

For more math explanation about the scale invariance (etc.), you could refer to [AET](https://openaccess.thecvf.com/content_CVPR_2019/papers/Zhang_AET_vs._AED_Unsupervised_Representation_Learning_by_Auto-Encoding_Transformations_Rather_CVPR_2019_paper.pdf) and [this paper](https://arxiv.org/pdf/1906.08628.pdf), hope this could solve your question.
