### ISSUE TITLE
关于基线CenterNet ResNet-18的官方mAP与这项工作中的mAP不一致

### ISSUE THREAD

**Issue by skro123** [cuiziteng/ECCV_AERIS#21]
您好，我注意到这篇工作非常有意义，
但有一个问题，mmdet官方的CenterNet ResNet-18 的mAP是25.9，参加这里https://github.com/open-mmlab/mmdetection/tree/main/configs/centernet，而这篇工作给出的是14.5，我对比了两者的配置文件，发现同样都是512大小的图像，这中间做出了修改？
即便不使用这个超分模块，官方基线的25.9也超过CenterNet-SwinTiny-AERIS (Stage2)的21.6。

**Comment by cuiziteng** [comment]
您好，十分谢谢您的关注，这个14.5的结果是在degradation的COCO数据集结果，并非原本COCO数据集的结果。

**Comment by skro123** [comment]
十分感谢您的回复，这对我理解该项工作很有意义。我明白了这个是在coco-d的数据集上的试验结果，我想问该方法是仅能用来处理degradation的数据吗？在普通的COCO数据集上能不能提高基线模型的性能？或者仅考虑分辨率的变化。
我在论文和issue中没有找到-d数据集的制作方法，从论文中看-d数据集不仅仅是降低分辨率，而且还加了各种模糊。
但我认为如果是超分辨的话，应该仅考虑分辨率的变化。加各种模糊的话属于图像增强或者恢复，训练过程中，给出了这些噪声图像的无噪声图像作为超分分支的标签，但实际情况下，图像的无噪声数据（用来重建的标签图像）很难获取。

**Comment by cuiziteng** [comment]
在普通的COCO上面，如果是CenterNet这种最终feature map分辨率较高的模型，也可以提升检测性能。

COCO-d和单独degradation数据的制作生成代码会在近期开源，主要是之前的代码整理起来比较麻烦，我近期开源一下这部分代码，因为COCO-d的生成有随机性，所以COCO-d会是唯一的数据集，但是单独加分辨率，噪声这些可以生成固定数据集。

**Comment by cuiziteng** [comment]
https://github.com/cuiziteng/ECCV_AERIS/blob/master/data_gen.py

，上传了模糊/噪声/分辨率的生成代码～

**Comment by skro123** [comment]
非常感谢！
