### ISSUE TITLE
Training Stage 1 and Stage 2

### ISSUE THREAD

**Issue by jiandandan001** [cuiziteng/ECCV_AERIS#4]
Thank you for sharing the code.

Why the training consists of two stages- stage1 and stage2?

What are the differences between Stage2 and Stage 1?

Thanks

**Comment by cuiziteng** [comment]
Thanks for interesting. The difference is where to place the ARRD's location on the network~

**Comment by jiandandan001** [comment]
> Thanks for interesting. The difference is where to place the ARRD's location on the network~

Thank you for your reply. Which one is better? Which one is the model used in the paper? Thanks

**Comment by cuiziteng** [comment]
Stage 2 is better than Stage 1, I show the number in the Table in README.md, please check~

**Comment by jiandandan001** [comment]
> Stage 2 is better than Stage 1, I show the number in the Table in README.md, please check~

thanks.
