### ISSUE TITLE
the parameter of stage2

### ISSUE THREAD

**Issue by dzgx** [cuiziteng/ECCV_AERIS#5]
Thank you for your work and code.
Would you please explain of  the parameter which is  scale_cfg in the stage2?

**Comment by cuiziteng** [comment]
Thanks for interesting, the scale_cfg is how to set the degradation resolution in training, in our code we set scale factor from 1 to 4, also you could set to other number, please read the supp in our paper~

**Comment by dzgx** [comment]
Thank you for your response.
I find that you update the scale_cfg in the stage1.

**Comment by cuiziteng** [comment]
Yeah, thank you
