### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mubashirITU** [cuiziteng/ECCV_AERIS#8]
When I run the tools/train.py in one 1080 TI GPU. I got the segmentation fault error. Can you kindly help me to solve this problem.
![image](https://user-images.githubusercontent.com/107511772/196904582-347cc303-deec-4a35-8bc0-908625c6a8cf.png)
![image](https://user-images.githubusercontent.com/107511772/196904688-cbd2e6d4-0350-4fc7-9555-fdea377c20a1.png)
![image](https://user-images.githubusercontent.com/107511772/196904820-e1b361fa-c29f-48a0-afa9-0c4104301660.png)

**Comment by cuiziteng** [comment]
Let me check that~

**Comment by mubashirITU** [comment]
I resolved this issue by reducing the num_wrokers to 2.

**Comment by mubashirITU** [comment]
Thanks.

**Comment by cuiziteng** [comment]
That's OK~
