### ISSUE TITLE
Train about steps among 1000 to Exp name

### ISSUE THREAD

**Issue by dzgx** [cuiziteng/ECCV_AERIS#9]
Would you please explain why training 1000 steps when it will exist it(the picture).
I choose config that is centernet_swint_stage2.py, but the mention ( Exp name: centernet_swint_stage2.py) 
![QQ截图20221020214225](https://user-images.githubusercontent.com/90265318/196966794-0c5fc145-34ca-42b4-a41a-e1f0aff52782.jpg)

**Comment by cuiziteng** [comment]
Hello, this is OK and just ignore it.
